import type { IBlogItem } from "./new.type";
import image from "../../assets/images/introduces/introduce_homepage.jpg";
export const BLOGS_DATA: IBlogItem[] = [
  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },

  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },

  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },

  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },

  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },

  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },

  {
    mainImage: image,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio blanditiis atque quibusdam, dolores iure nostrum sed voluptatibus magni cupiditate, totam neque porro sequi voluptatum alias id sint explicabo! Aut, quis? Commodi placeat vel est voluptatem excepturi labore. Recusandae ducimus beatae nobis debitis magni eum optio, molestiae, dolorum ad ea, necessitatibus quas architecto consectetur earum quia impedit consequuntur reprehenderit! Asperiores, tempore! Sapiente eos fugit vero labore adipisci perspiciatis doloribus voluptatem ut repellendus neque quia id ipsam possimus repudiandae veniam tempora alias, assumenda aperiam esse, reprehenderit odit nam molestiae distinctio? Harum, itaque?",
    contentImage: [image, image, image],
    createAt: new Date().toISOString(),
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
  },
];
